# Generated by Django 3.2.5 on 2021-08-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20210814_0208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='flights',
            new_name='Flight',
        ),
    ]
